### ISSUE TITLE
support ctypes.0.7.0+

### ISSUE THREAD

**Issue by avsm** [janestreet/async_ssl#17]
there's currently a hard `<0.6.0` constraint for ctypes here, resulting in:

```
  ↘  downgrade ctypes         0.7.0 to 0.5.1  [required by async_ssl]
```

what's causing this upper bound?

**Comment by diml** [comment]
Basically ctypes 0.6 breaks compatibility and we haven't upgraded our internal version yet.

/cc @tari3x

**Comment by vbmithr** [comment]
+1

**Comment by bogdan2412** [comment]
I think the latest revision pushed a few days ago needs a newer ctypes.
```
# File "bindings/ffi_bindings.ml", line 51, characters 24-31:
# Error: Unbound value F.@->
```
When I removed the {>= "0.4.0" & < "0.6.0"} restriction from the ctypes depends, compilation succeeded.

**Comment by diml** [comment]
Indeed, I'm removing the constraint. async_ssl now builds with ctypes >= 0.7.0 so I'm closing this issue
