### ISSUE TITLE
Possible Async_ssl memory leak

### ISSUE THREAD

**Issue by pdonadeo** [janestreet/async_ssl#21]
I'm writing a web crawler and I can't complete my job because it leaks memory. The libraries I use are Core + Async, conduit and cohttp. First of all I searched the culprit in my program itself, then in cohttp and finally in conduit, but it seems that it's Async_ssl to leak memory.

I wrote a simple program (less than 100 lines) using only Async_ssl and some really standard Async machinery, [you can find it in this gist](https://gist.github.com/pdonadeo/1c960bd889c12014ed4db51486c32bc4).

The program runs two "loops": the first requests a GET to github.com more or less once per second. The second loop is a Gc.compact once per minute.

After only 228 minutes and 5253 requests it passes from 18 MB of resident RAM to 687M.

![Screenshot of htop](http://www.donadeo.net/static/2017/async_ssl_leaks_memory.png)

I'm using Async_ssl 113.33.07 and OCaml 4.02.3, everything installed with OPAM on a Fedora 24.

I really need to solve this problem and I want to help the debugging process, but I'm not an expert of ctypes so I need help: where do I should start from?

**Comment by vbmithr** [comment]
See #13

**Comment by pdonadeo** [comment]
@vbmithr What is the last version of Core/Async/OCaml you advice me to try?

**Comment by vbmithr** [comment]
On 06/01/2017 15:11, Paolo Donadeo wrote:
> @vbmithr <https://github.com/vbmithr> What is the last version of
> Core/Async/OCaml you advice me to try?

Dev version of Janestreet libs + 4.03.0.

The stable version of janestreet works on 4.04, where you can use
spacetime to debug a memory leak, but there is a know memory leak in
async_ssl in this version.

I say this because in my case, I have a memory leak I'd like to
investigate with spacetime, on a program that uses Core/Async, but
unfortunately devel Janestreet libraries does not work on 4.04.

**Comment by pdonadeo** [comment]
@vbmithr thanks, I'm going to try ASAP, i.e. right now.

Can I keep open this issue until I can confirm the memory bug is gone?

**Comment by pdonadeo** [comment]
> Dev version of Janestreet libs + 4.03.0.

Is it the [master branch](https://github.com/janestreet/async_ssl.git) of this repo?

**Comment by vbmithr** [comment]
On 06/01/2017 15:25, Paolo Donadeo wrote:
> Is it the master branch <https://github.com/janestreet/async_ssl.git> of
> this repo?

Use `opam repo add js git://github.com/janestreet/opam-repository`

**Comment by pdonadeo** [comment]
I just completed a test, compiling with JS dev repo. The problem is still there.

After:
```
real    795m31.669s
user    3m24.691s
sys     0m34.531s
```
and 18167 requests the process ended with 2258.9 GB of RSS RAM.

![VmRSS graph over 13 hours](http://www.donadeo.net/static/2017/625_VmRSS.png)

The graph shows a **very strange** behaviour: every 2 hours the consumed RAM has a step of about 300 mb.

Any ideas?

**Comment by pdonadeo** [comment]
This is a zoom between two steps.

![VmRSS graph over 13 hours](http://www.donadeo.net/static/2017/625_VmRSS_zoom.png)

**Comment by vbmithr** [comment]
Le 07/01/2017 à 12:08, Paolo Donadeo a écrit :
> Any ideas?

No, but amazing, because my problem might very well be the same as
yours! I'm glad that you found this!

-- 
Vincent

**Comment by pdonadeo** [comment]
@vbmithr wrote:
> Haha, it looks fractal :p

Yes, and it's really disappointing, I've never seen such a behaviour in a simple program like this. Also the library binding is supposed to be a wrapper or little more.

Now I'm running this:
https://gist.github.com/pdonadeo/b56688193e5406d5d59d83487376e902

It's the same program but it does not make any use of SSL. Just to verify that the culprit is actually Async_ssl and not another Async component. I'll make you know.

It has been compiled against JS dev repo as you suggested.


-- 
Paolo

**Comment by vbmithr** [comment]
Le 08/01/2017 à 17:38, Paolo Donadeo a écrit :
> It's the same program but it does not make any use of SSL. Just to
> verify that the culprit is actually Async_ssl and not another Async
> component. I'll make you know.

I'm trying to add an async backend to http://github.com/mirleft/ocaml-tls

Seems a better way long term than relying to bindings anyway.

-- 
Vincent

**Comment by pdonadeo** [comment]
It's a very interesting idea. Meanwhile, it seems we have a problem not stricty related to Async_ssl.

Here you can find a chart of the non SSL test running:
https://docs.google.com/spreadsheets/d/1rwUicVV-Geh4OfEPKMBN6j60KOqfbm7YT1Q_UjFoTpo/edit?usp=sharing

It's not updated "live" (I sometimes upload new data, and it's still running), but you can see the memory remains bounded, since every 60 seconds a `Gc.compact` collects the garbage.

But in an hour we have a step. Maybe there are two memory leaks, one in Async_ssl (removed in this second test) but the other is still there. Tomorrow I'll post the complete graph.

**Comment by pdonadeo** [comment]
@vbmithr I consider the non-SSL test complete. After more than 17 hours (1039 minutes) and 60.512 requests the result is this:

![VmRSS graph over 17 hours](http://www.donadeo.net/static/2017/1219_VmRSS.png)

This is **not** a memory leak, IMHO.

The original graph is here: https://docs.google.com/spreadsheets/d/1rwUicVV-Geh4OfEPKMBN6j60KOqfbm7YT1Q_UjFoTpo/edit#gid=137227378

**Comment by tari3x** [comment]
This is a known issue, the fix should make it into the next public release.

**Comment by diml** [comment]
@vbmithr, @avsm and @samoht where talking about getting an intern to port async\_ssl to ocaml-tls. Just mentioning this here in case you are both doing the same thing

**Comment by vbmithr** [comment]
Le 09/01/2017 à 16:28, Jérémie Dimino a écrit :
> Just mentioning this here in case you are both doing the same thing

Thank you, that sounds the same indeed.

-- 
Vincent

**Comment by timclassic** [comment]
@pdonadeo, @vbmithr: I'm responsible for the fix that @tari3x referenced.  I discovered that the [`get_peer_certificate` function in `src/ffi.ml`](../blob/10983f43188e94fe0567b8db32ce861d2d858ac9/src/ffi.ml#L398) does not add a finalizer to free the returned X509 structure, causing a leak of this data with each call to `Ssl.Connection.peer_certificate`.  See `SSL_get_peer_certificate(3)`.

However, the gist above doesn't appear to use `Ssl.Connection.peer_certificate`, so I'm not convinced that this patch will help here.  @pdonadeo, can you confirm that your test case is still current?

**Comment by pdonadeo** [comment]
@timclassic yes, I can confirm that the small snippet above using Async_ssl shows an evident memory leak, while the non-SSL version keeps the memory bounded, at least during the first 17 hours of test.

**Comment by timclassic** [comment]
@pdonadeo and @vbmithr, I plan to look a bit further into this tomorrow while it is relatively fresh in my mind.

**Comment by pdonadeo** [comment]
@timclassic thanks!

**Comment by vbmithr** [comment]
Le 10/01/2017 à 22:58, Tim Stewart a écrit :
> @pdonadeo <https://github.com/pdonadeo> and @vbmithr
> <https://github.com/vbmithr>, I plan to look a bit further into this
> tomorrow while it is relatively fresh in my mind.

Thanks indeed!

-- 
Vincent

**Comment by pdonadeo** [comment]
FYI I'm running a still more reduced test:

https://gist.github.com/pdonadeo/78eae3520fac9b7983827c8257158e31

In this test only 2 functions are called: `Ssl.client` and `Async_ssl.Ssl.Connection.close`, i.e. the SSL connection is opened and closed in half a second. This effort is aimed to isolate the culprit function from an external point of view.

**Comment by pdonadeo** [comment]
And the result is that the leak is still there, only opening and closing the connection.
```
real    589m52.866s 
user    4m1.476s 
sys     0m38.176s
```
Opened connections: 27.744. No file descriptor leaked, but the memory (RSS) is:

![VmRSS graph over 17 hours](http://www.donadeo.net/static/2017/4222_VmRSS.png)

Complete graph and data here: https://docs.google.com/spreadsheets/d/1DzSs1WAMeMkJlDE1NiBOBREmQGot4l7hpKOX60lS66I/edit#gid=137227378

**Comment by vbmithr** [comment]
On 12/01/2017 10:00, Paolo Donadeo wrote:
> And the result is that the leak is still there

Would be a good test for Spacetime, finding memory leaks in Jane Street
code with Jane Street tools ;)

**Comment by timclassic** [comment]
@pdonadeo @vbmithr Another task ran longer than expected. I will look at this first thing in the morning and see if I can replicate.

**Comment by timclassic** [comment]
@pdonadeo I tried your recent reduced test and noticed that it has no code to close the TCP connections.  I tested with a local HTTP server and the test client continued to create connections, but none would close until I killed the client (or the server).  I'm not sure how long github.com allows connections to stay alive, but perhaps these open connections are related to the memory growth.

I changed `Tcp.connect` to `Tcp.with_connection` so that connections would close: https://gist.github.com/timclassic/1c5e687b6e3f305a6b18295b5e9c6bef

A diff that makes the change clearer (it ignores whitespace): https://gist.github.com/timclassic/8a52d8ef86d2cb0a90a0ec318d79af81

Would you mind retrying the test with my version of the code in your environment?

**Comment by pdonadeo** [comment]
@timclassic of course, I just started the test, thanks.

**Comment by pdonadeo** [comment]
Sorry for the delay. Unfortunately the test died after 40 minutes with this nonsense exception:

```
(monitor.ml.Error
 (src/core_unix.ml.Inet_addr.Get_inet_addr github.com "host not found")
 ("Called from file \"src/deferred1.ml\", line 20, characters 40-45"
  "Called from file \"src/job_queue.ml\", line 159, characters 6-47"))
```

I'm going to restart it tonight.

**Comment by diml** [comment]
BTW, all our development packages now build with both 4.03 and 4.04, so you can use spacetime with our bleeding edge code. I'm currently working on making them work with 4.05 as well

**Comment by timclassic** [comment]
@pdonadeo Did you get a chance to restart your test and get some usable results?

**Comment by timclassic** [comment]
Oh, and recently-pushed https://github.com/janestreet/async_ssl/commit/74ad7723f125d94e9b988c1e0f4b123105ae693d represents the peer certificate memory leak fix mentioned in https://github.com/janestreet/async_ssl/issues/21#issuecomment-271365140.  I still believe this issue is unrelated.

**Comment by pdonadeo** [comment]
@timclassic I'm sorry, it's a very busy period, I totally forgot this issue. I just restarted the test you provided.

**Comment by pdonadeo** [comment]
Brief update only to confirm that the test is running since more than five hours, and actually in this moment the leak is not observable.

I'm going to test for at least 12 hours.

**Comment by pdonadeo** [comment]
Conclusion, after about 22 hours:

```
real    1316m12.358s
user    4m28.826s
sys     1m35.999s
```

and 62604 open/close, no evidence of memoty leak.

![VmRSS graph over 17 hours](https://dl.dropboxusercontent.com/u/1449413/20467_VmRSS.png)

**Comment by timclassic** [comment]
@pdonadeo Great!  If you're satisfied that there is no memory leak, would you mind closing this issue?

Also, the image in https://github.com/janestreet/async_ssl/issues/21#issuecomment-277200596 is broken for me.

**Comment by pdonadeo** [comment]
@timclassic damn, I'm going to repost the image.

**Comment by pdonadeo** [comment]
@timclassic I'm going to test [my original program](https://gist.github.com/pdonadeo/1c960bd889c12014ed4db51486c32bc4) with the last patches.

**Comment by pdonadeo** [comment]
```ppx_core``` doesn't compile with OCaml 4.03.0 with JS OPAM repository. I'm switching to 4.04.0.

**Comment by pdonadeo** [comment]
And... with 4.04.0 + JS:

```[ERROR] The compilation of ppx_ast failed at "jbuilder build-package ppx_ast -j 24".```

:unamused:

**Comment by yminsky** [comment]
On what platform? I've built the full suite of packages on OS X recently.
Also, could you report the full details of the failure?

**Comment by trefis** [comment]
> ppx_core doesn't compile with OCaml 4.03.0 with JS OPAM repository.

Can you tell us the package version number and the actual compilation error?
Also, maybe we should discuss that specific issue on http://github.com/janestreet/ppx_core/issues .

**Comment by vbmithr** [comment]
On 07/02/2017 11:21, Paolo Donadeo wrote:
> And... with 4.04.0 + JS:
> 
> |[ERROR] The compilation of ppx_ast failed at "jbuilder build-package
> ppx_ast -j 24".|
> 
> 😒
> 

See https://github.com/janestreet/opam-repository/issues/4

**Comment by pdonadeo** [comment]
For @yminsky 

The platform is CentOS 7.3, opam version 1.2.2, OCaml compiler versione 4.04.0, with these repositories:
```
$ opam repo list
  10 [git]           js     git://github.com/janestreet/opam-repository
   0 [http]     default     https://opam.ocaml.org
```
Attached the [scrollback from tmux](https://github.com/janestreet/async_ssl/files/757862/tmux_scrollback.txt) and the [standard error from OPAM](https://github.com/janestreet/async_ssl/files/757864/ppx_ast-720-1872ec.err.txt).

**Comment by trefis** [comment]
The version you're trying to install was indeed broken, so was ppx_core, but both have been fixed this morning.
Try updating, the version you want to install is 114.31+04.

**Comment by pdonadeo** [comment]
@yminsky @trefis I'm running the original test, thanks for the hints.

**Comment by pdonadeo** [comment]
I just completed The last test, about 10 hours long and exactly 12.662 requests. Source [code here](https://gist.github.com/pdonadeo/81f3483bbd615aeeecfdec93ab6025dc).

The used RAM never grows, see the thart below:

![VmRSS graph over 10 hours](https://docs.google.com/spreadsheets/d/1JhMMaYqKp-yurBptZEhKrYYPK49ruA1KegIHdPkPZho/pubchart?oid=1965687219&format=image)

I think we can close this issue! :raised_hands:

Thanks to you all.
